CuaHangSach/CuaHangSach/Areas/Admin/Controllers/QuanLyChiTietDonHangController.cs
using CuaHangSach.Databases;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSach.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class QuanLyChiTietDonHangController : Controller
    {
        QLBANSACHEntities db = new QLBANSACHEntities();
        public ActionResult ChiTietDonHang()
        {
            var ListChiTietDonHang = db.CHITIETDONHANGs.ToList();
            if (ListChiTietDonHang.Count > 0)
            {
                return View(ListChiTietDonHang);
            }
            else
            {
                return RedirectToAction("ChiTietDonHangRong");
            }
        }
        public ActionResult XoaChiTietDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITIETDONHANG chitietdonhang = db.CHITIETDONHANGs.Find(id);
            if (chitietdonhang == null)
            {
                return HttpNotFound();
            }
            return View(chitietdonhang);
        }
        [HttpPost, ActionName("XoaChiTietDonHang")]
        [ValidateAntiForgeryToken]
        public ActionResult XoaChiTietDonHang(int id)
        {
            CHITIETDONHANG chitietdonhang = db.CHITIETDONHANGs.Find(id);
            db.CHITIETDONHANGs.Remove(chitietdonhang);
            db.SaveChanges();
            return RedirectToAction("ChiTietDonHang");
        }
        public ActionResult ChiTietDonHangRong()
        {
            return View();
        }
    }
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyChiTietDonHang/ChiTietDonHang.cshtml
@model IEnumerable<CuaHangSach.Databases.CHITIETDONHANG>

@{
    ViewBag.Title = "Chi Tiết Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<marquee direction="right" scrollamount=20>
    <h1 style="color:aqua">Quản Lý Chi Tiết Đơn Hàng</h1>
</marquee>
<hr />
<table class="table table-bordered">
    <tr style="color:yellow">
        <th>
            Mã Khách Hàng
        </th>
        <th>
            Tên Người Đặt
        </th>
        <th>
            Ảnh Bìa
        </th>
        <th>
            Tên Sách
        </th>
        <th>
            Giá Bán
        </th>
        <th>
            Số Lượng
        </th>
        <th>
            Tổng
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="color:black">
            <td>
                @Html.DisplayFor(modelItem => item.MaDDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DONDATHANG.HoTenKH)
            </td>
            <td>
                <img src="~/Content/Images/Sach/@item.SACH.AnhBia" alt="cover page" width="80" />
            </td>
            @{
                string tensach = item.SACH.TenSach;
            }
            @if (tensach.Length >= 25)
            {
                tensach = tensach.ToString().Substring(0, 25);
            }
            <td title="@item.SACH.TenSach">
                @tensach...
            </td>
            <td>
                @item.SACH.GiaBan đ
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @item.DonGia đ
            </td>
            <td>
                <a class="skew-button delete-link" href="XoaChiTietDonHang/@item.MaCTDH" title="Xóa Chi Tiết Đơn Hàng Này"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    }
</table>
<hr />

@section Scripts{
    <script>
        $('.delete-link').click(function (e) {
            var a_href = $(this).attr('href'); /* Lấy giá trị của thuộc tính href */
            e.preventDefault(); /* Không thực hiện action mặc định */
            $.ajax({ /* Gửi request lên server */
                url: a_href, /* Nội dung trong Delete.cshtml cụ thể là deleteModal div được server trả về */
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                success: function (data) { /* Sau khi nhận được giá */
                    $('.body-content').prepend(data); /* body-content div (định nghĩa trong _Layout.cshtml) sẽ thêm deleteModal div vào dưới cùng */
                    $('#deleteModal').modal('show'); /* Hiển thị deleteModal div dưới kiểu modal */
                }
            });
        });
    </script>
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyChiTietDonHang/ChiTietDonHangRong.cshtml
@{
    ViewBag.Title = "Chi Tiết Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<marquee direction="right" scrollamount=20>
    <h1 style="color:aqua">Quản Lý Chi Tiết Đơn Hàng</h1>
</marquee>
<hr />
<div class="alert alert-danger">
    Không có dữ liệu trong hệ thống.
</div>

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyChiTietDonHang/XoaChiTietDonHang.cshtml
@model CuaHangSach.Databases.CHITIETDONHANG

@{
    ViewBag.Title = "XoaChiTietDonHang";
    Layout = null;
}

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" style="color:red"><span class="glyphicon glyphicon-warning-sign"></span> Cảnh Báo</h4>
            </div>
            <div class="modal-body">
                <h3>Bạn có chắc muốn xóa chi tiết đơn hàng này không?</h3>
                <div>
                    <hr />
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th style="color:blue">Mã Khách Hàng:</th>
                            <td>@Html.DisplayFor(model => model.MaDDH)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Tên Người Đặt:</th>
                            <td>@Html.DisplayFor(model => model.DONDATHANG.HoTenKH)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Tên Sách:</th>
                            <td>@Html.DisplayFor(model => model.SACH.TenSach)</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("XoaChiTietDonHang", "QuanLyChiTietDonHang", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center pull-right">
                        <button type="submit" class="skew-button" title="Xóa"><span class="glyphicon glyphicon-trash"></span></button>
                        <button type="button" class="skew-button" data-dismiss="modal" title="Hủy"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>