CuaHangSach/CuaHangSach/Controllers/QuanLyCuaHangController.cs
using CuaHangSach.Databases;
using CuaHangSach.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSach.Controllers
{
    public class QuanLyCuaHangController : Controller
    {
        QLBANSACHEntities db = new QLBANSACHEntities();
        public ActionResult CuaHang(int? page)
        {
            var ListSach = db.SACHes.ToList();
            int PageNumber = (page ?? 1);
            int PageSize = 8;
            return View(ListSach.ToPagedList(PageNumber, PageSize));
        }
        public ActionResult TimKiemSach(string search)
        {
            var ListSach = from s in db.SACHes select s;
            if (!String.IsNullOrEmpty(search))
            {
                ListSach = db.SACHes.Where(s => s.TenSach.Contains(search));
            }
            else
            {
                return RedirectToAction("Oops", "Order");
            }
            ViewBag.SearchTerm = search;
            return View(ListSach.ToList());
        }
        public ActionResult ThongTinSach(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            SACH sach = db.SACHes.Find(id);
            return View(sach);
        }
    }
}

CuaHangSach/CuaHangSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link href="~/Content/Css/Button/Skewed_Button.css" rel="stylesheet" />
    <link type="text/css" media="all" href="~/Content/Css/404.css" rel="stylesheet" />
    <link href="~/Content/Css/Body.css" rel="stylesheet" />
    <link href="~/Content/Css/Footer.css" rel="stylesheet" />
    <link href="~/Content/Css/Header.css" rel="stylesheet" />
    <link href="~/Content/Css/KhoSach.css" rel="stylesheet" />
    <link href="~/Content/Css/List_Images.css" rel="stylesheet" />
    <link href="~/Content/Css/Loading.css" rel="stylesheet" />
    <link href="~/Content/Css/Search_Form.css" rel="stylesheet" />
    <link href="~/Content/Css/Skewed_Menu.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <script type="text/javascript">
        $(window).load(function () {
            $('.progressbar').fadeOut(50).remove();
        })
    </script>
    <title>@ViewBag.Title - Sách</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="progressbar">
        <div class="stylization"></div>
    </div>

    <div class="head">
        <nav class="skew-menu">
            <ul>
                <li><a href="/Home/Index"><span class="glyphicon glyphicon-home"></span>Trang Chủ</a></li>
                <li><a href="/QuanLyCuaHang/CuaHang"><span class="glyphicon glyphicon-shopping-cart"></span>Cửa Hàng</a></li>
                <li><a href="/Home/About"><span class="glyphicon glyphicon-info-sign"></span>Thông Tin</a></li>
                <li><a href="/Home/Contact"><span class="glyphicon glyphicon-envelope"></span>Liên Hệ</a></li>
                @if (Request.IsAuthenticated)
                {
                    <li><a href="/Admin/QuanLyKhoSach/KhoSach"><span class="glyphicon glyphicon-user"></span>Xin Chào: @User.Identity.Name!</a></li>
                    <li><a href="/TaiKhoan/DangXuat"><span class="glyphicon glyphicon-log-out"></span>Đăng Xuất</a></li>
                }
                else
                {
                    <li><a href="/TaiKhoan/DangNhap"><span class="glyphicon glyphicon-log-in"></span>Đăng Nhập</a></li>
                    <li><a href="/TaiKhoan/DangKy"><span class="glyphicon glyphicon-list-alt"></span>Đăng Ký</a></li>
                }
            </ul>
        </nav>

        @using (Html.BeginForm("TimKiemSach", "QuanLyCuaHang", FormMethod.Get, new { @class = "searchform cf", role = "search", onsubmit = "return empty();" }))
        {
            <form class="searchform cf">
                <input type="text" name="search" value="@ViewBag.SearchTerm" placeholder="Bạn đang tìm sách gì?">
                <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </form>
        }
    </div>

    <div class="container body-content">
        @RenderBody()
        <footer>
            <div class="splitter"></div>
            <ul>
                <li>
                    <div class="icon" data-icon="E"></div>
                    <div class="text">
                        <h4>About</h4>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eu sollicitudin pretium. Nam scelerisque arcu at dui porttitor, non viverra sapien pretium. Nunc nec dignissim nunc. Sed eget est purus. Sed convallis, metus in dictum feugiat, odio orci rhoncus metus. <a href="#">Read more</a></div>
                    </div>
                </li>
                <li>
                    <div class="icon" data-icon="a"></div>
                    <div class="text">
                        <h4>Archive</h4>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eu sollicitudin pretium. Nam scelerisque arcu at dui porttitor, non viverra sapien pretium. Nunc nec dignissim nunc. Sed eget est purus. Sed convallis, metus in dictum feugiat, odio orci rhoncus metus. <a href="#">Read more</a></div>
                    </div>
                </li>
                <li>
                    <div class="icon" data-icon="s"></div>
                    <div class="text">
                        <h4>Cloud</h4>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eu sollicitudin pretium. Nam scelerisque arcu at dui porttitor, non viverra sapien pretium. Nunc nec dignissim nunc. Sed eget est purus. Sed convallis, metus in dictum feugiat, odio orci rhoncus metus. <a href="#">Read more</a></div>
                    </div>
                </li>
            </ul>

            <div class="bar">
                <div class="bar-wrap">
                    <ul class="links">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">License</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Advertise</a></li>
                        <li><a href="#">About</a></li>
                    </ul>

                    <div class="social pull-right">
                        <a href="#" class="fb">
                            <span data-icon="f" class="icon"></span>
                            <span class="info">
                                <span class="follow">Become a fan Facebook</span>
                                <span class="num">9,999</span>
                            </span>
                        </a>

                        <a href="#" class="tw">
                            <span data-icon="T" class="icon"></span>
                            <span class="info">
                                <span class="follow">Follow us Twitter</span>
                                <span class="num">9,999</span>
                            </span>
                        </a>

                        <a href="#" class="rss">
                            <span data-icon="R" class="icon"></span>
                            <span class="info">
                                <span class="follow">Subscribe RSS</span>
                                <span class="num">9,999</span>
                            </span>
                        </a>
                    </div>
                    <div class="clear"></div>
                    <div class="copyright">&copy;  2014 All Rights Reserved</div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/Content/Js/List_Images.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>