CuaHangSach/CuaHangSach/Areas/Admin/Controllers/QuanLyDonHangController.cs
using CuaHangSach.Databases;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSach.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class QuanLyDonHangController : Controller
    {
        QLBANSACHEntities db = new QLBANSACHEntities();
        public ActionResult DonHang()
        {
            var ListDonHang = db.DONDATHANGs.ToList();
            if (ListDonHang.Count > 0)
            {
                return View(ListDonHang);
            }
            else
            {
                return RedirectToAction("DonHangRong");
            }
        }
        public ActionResult ChinhSuaDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONDATHANG dondathang = db.DONDATHANGs.SingleOrDefault(s => s.MaDDH == id);
            return View(dondathang);
        }
        [HttpPost, ActionName("ChinhSuaDonHang")]
        [ValidateAntiForgeryToken]
        public ActionResult ChinhSuaDonHang(int id)
        {
            var dondathangUpdate = db.DONDATHANGs.Find(id);
            if (TryUpdateModel(dondathangUpdate, "", new string[] { "HoTenKH", "DienThoaiKH", "EmailKH", "DiaChiKH", "DaThanhToan", "TinhTrangGiaoHang", "NgayGiao" }))
            {
                try
                {
                    db.Entry(dondathangUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Error Save Data");
                }
            }
            return RedirectToAction("DonHang");
        }
        public ActionResult XoaDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONDATHANG dondathang = db.DONDATHANGs.Find(id);
            if (dondathang == null)
            {
                return HttpNotFound();
            }
            return View(dondathang);
        }
        [HttpPost, ActionName("XoaDonHang")]
        [ValidateAntiForgeryToken]
        public ActionResult XoaDonHang(int id)
        {
            DONDATHANG dondathang = db.DONDATHANGs.Find(id);
            db.DONDATHANGs.Remove(dondathang);
            db.SaveChanges();
            return RedirectToAction("DonHang");
        }
        public ActionResult DonHangRong()
        {
            return View();
        }
    }
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyDonHang/ChinhSuaDonHang.cshtml
@model CuaHangSach.Databases.DONDATHANG

@{
    ViewBag.Title = "Chỉnh Sửa Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

<h2 style="color:aqua">Chỉnh Sửa Đơn Hàng</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="padding-left:10px" class="text-warning">Dấu * là bắt buộc!</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="color:red">
            @Html.LabelFor(model => model.HoTenKH, "*Họ và Tên:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:red">
            @Html.LabelFor(model => model.DienThoaiKH, "*Điện Thoại:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoaiKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.EmailKH, "Email:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:red">
            @Html.LabelFor(model => model.DiaChiKH, "*Địa Chỉ:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.DaThanhToan, "Tình Trạng Thanh Toán:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="color:black">
                @Html.RadioButtonFor(model => model.DaThanhToan, "true", new { id = "yes" })
                @Html.Label("yes", "Đã Thanh Toán")
                @Html.RadioButtonFor(model => model.DaThanhToan, "false", new { id = "no" })
                @Html.Label("no", "Chưa Thanh Toán")
                @Html.ValidationMessageFor(model => model.DaThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.TinhTrangGiaoHang, "Tình Trạng Giao Hàng:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="color:black">
                @Html.RadioButtonFor(model => model.TinhTrangGiaoHang, "true", new { id = "yes" })
                @Html.Label("yes", "Đã Giao Hàng")
                @Html.RadioButtonFor(model => model.TinhTrangGiaoHang, "false", new { id = "no" })
                @Html.Label("no", "Chưa Giao Hàng")
                @Html.ValidationMessageFor(model => model.TinhTrangGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.NgayGiao, "Ngày Giao:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <button class="skew-button" type="submit" title="Luư"><span class="glyphicon glyphicon-save"></span></button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về", "DonHang")
</div>
<hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyDonHang/DonHang.cshtml
@model IEnumerable<CuaHangSach.Databases.DONDATHANG>

@{
    ViewBag.Title = "Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<marquee direction="right" scrollamount=20>
    <h1 style="color:aqua">Quản Lý Đơn Hàng</h1>
</marquee>
<hr />
<table class="table table-bordered">
    <tr style="color:yellow">
        <th>
            Mã Khách Hàng
        </th>
        <th>
            Họ và Tên
        </th>
        <th>
            Điện Thoại
        </th>
        <th>
            Email
        </th>
        <th>
            Địa Chỉ
        </th>
        <th>
            Ngày Đặt
        </th>
        <th>
            Ngày Giao
        </th>
        <th>
            Tình Trạng Thanh Toán
        </th>
        <th>
            Tình Trạng Giao Hàng
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="color:black">
            <td>
                @Html.DisplayFor(modelItem => item.MaDDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoTenKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoaiKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChiKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @if (item.DaThanhToan == true)
                {
                    <span>Đã Thanh Toán</span>
                }
                else
                {
                    <span>Chưa Thanh Toán</span>
                }
            </td>
            <td>
                @if (item.TinhTrangGiaoHang == true)
                {
                    <span>Đã Giao Hàng</span>
                }
                else
                {
                    <span>Chưa Giao Hàng</span>
                }
            </td>
            <td>
                <a class="skew-button" href="ChinhSuaDonHang/@item.MaDDH" title="Chỉnh Sửa Đơn Hàng"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="skew-button delete-link" href="XoaDonHang/@item.MaDDH" title="Xóa Đơn Hàng Này"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    }
</table>
<hr />

@section Scripts{
    <script>
        $('.delete-link').click(function (e) {
            var a_href = $(this).attr('href'); /* Lấy giá trị của thuộc tính href */
            e.preventDefault(); /* Không thực hiện action mặc định */
            $.ajax({ /* Gửi request lên server */
                url: a_href, /* Nội dung trong Delete.cshtml cụ thể là deleteModal div được server trả về */
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                success: function (data) { /* Sau khi nhận được giá */
                    $('.body-content').prepend(data); /* body-content div (định nghĩa trong _Layout.cshtml) sẽ thêm deleteModal div vào dưới cùng */
                    $('#deleteModal').modal('show'); /* Hiển thị deleteModal div dưới kiểu modal */
                }
            });
        });
    </script>
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyDonHang/DonHangRong.cshtml
@{
    ViewBag.Title = "Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<marquee direction="right" scrollamount=20>
    <h1 style="color:aqua">Quản Lý Đơn Hàng</h1>
</marquee>
<hr />
<div class="alert alert-danger">
    Không có dữ liệu trong hệ thống.
</div>

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyDonHang/XoaDonHang.cshtml
@model CuaHangSach.Databases.DONDATHANG

@{
    ViewBag.Title = "Xóa Đơn Hàng";
    Layout = null;
}

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" style="color:red"><span class="glyphicon glyphicon-warning-sign"></span> Cảnh Báo</h4>
            </div>
            <div class="modal-body">
                <h3>Bạn có chắc muốn xóa đơn hàng này không?</h3>
                <div>
                    <hr />
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th style="color:blue">Người Đặt:</th>
                            <td>@Html.DisplayFor(model => model.HoTenKH)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Tình Trạng Thanh Toán:</th>
                            <td>
                                @if (Model.DaThanhToan == true)
                                {
                                    <span>Đã Thanh Toán</span>
                                }
                                else
                                {
                                    <span>Chưa Thanh Toán</span>
                                }
                            </td>
                        </tr>
                        <tr>
                            <th style="color:blue">Tình Trạng Giao Hàng:</th>
                            <td>
                                @if (Model.TinhTrangGiaoHang == true)
                                {
                                    <span>Đã Giao Hàng</span>
                                }
                                else
                                {
                                    <span>Chưa Giao Hàng</span>
                                }
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("XoaDonHang", "QuanLyDonHang", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center pull-right">
                        <button type="submit" class="skew-button" title="Xóa"><span class="glyphicon glyphicon-trash"></span></button>
                        <button type="button" class="skew-button" data-dismiss="modal" title="Hủy"><span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>