CuaHangSach/CuaHangSach/Areas/Admin/Controllers/QuanLyNhaXuatBanController.cs
using CuaHangSach.Databases;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CuaHangSach.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class QuanLyNhaXuatBanController : Controller
    {
        QLBANSACHEntities db = new QLBANSACHEntities();
        public ActionResult NhaXuatBan(int? page)
        {
            var ListNhaXuatBan = db.NHAXUATBANs.ToList();
            int PageNumber = (page ?? 1);
            int PageSize = 6;
            return View(ListNhaXuatBan.ToPagedList(PageNumber, PageSize));
        }
        public ActionResult ChinhSuaNhaXuatBan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHAXUATBAN nhaxuatban = db.NHAXUATBANs.SingleOrDefault(s => s.MaNXB == id);
            return View(nhaxuatban);
        }
        [HttpPost, ActionName("ChinhSuaNhaXuatBan")]
        [ValidateAntiForgeryToken]
        public ActionResult ChinhSuaNhaXuatBan(int id)
        {
            var nhaxuatbanUpdate = db.NHAXUATBANs.Find(id);
            if (TryUpdateModel(nhaxuatbanUpdate, "", new string[] { "TenNXB", "DiaChiNXB", "DienThoaiNXB" }))
            {
                try
                {
                    db.Entry(nhaxuatbanUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Error Save Data");
                }
            }
            return RedirectToAction("NhaXuatBan");
        }
        public ActionResult XoaNhaXuatBan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHAXUATBAN nhaxuatban = db.NHAXUATBANs.Find(id);
            if (nhaxuatban == null)
            {
                return HttpNotFound();
            }
            return View(nhaxuatban);
        }
        [HttpPost, ActionName("XoaNhaXuatBan")]
        [ValidateAntiForgeryToken]
        public ActionResult XoaNhaXuatBan(int id)
        {
            NHAXUATBAN nhaxuatban = db.NHAXUATBANs.Find(id);
            db.NHAXUATBANs.Remove(nhaxuatban);
            db.SaveChanges();
            return RedirectToAction("NhaXuatBan");
        }
        [HttpPost, ActionName("ThemNhaXuatBan")]
        public ActionResult ThemNhaXuatBan([Bind(Include = "TenNXB, DiaChiNXB, DienThoaiNXB")]NHAXUATBAN nhaxuatban)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.NHAXUATBANs.Add(nhaxuatban);
                    db.SaveChanges();
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Error Save Data");
            }
            return RedirectToAction("NhaXuatBan");
        }
        public ActionResult ThemNhaXuatBan()
        {
            return View();
        }
    }
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyNhaXuatBan/ChinhSuaNhaXuatBan.cshtml
@model CuaHangSach.Databases.NHAXUATBAN

@{
    ViewBag.Title = "Chỉnh Sửa Nhà Xuất Bản";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

<h2 style="color:aqua">Chỉnh Sửa Nhà Xuất Bản</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="padding-left:10px" class="text-warning">Dấu * là bắt buộc!</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="color:red">
            @Html.LabelFor(model => model.TenNXB, "*Tên Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.DiaChiNXB, "Địa Chỉ Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.DienThoaiNXB, "Điện Thoại Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoaiNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <button class="skew-button" type="submit" title="Luư"><span class="glyphicon glyphicon-save"></span></button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về", "NhaXuatBan")
</div>
<hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyNhaXuatBan/NhaXuatBan.cshtml
@model PagedList.IPagedList<CuaHangSach.Databases.NHAXUATBAN>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Nhà Xuất Bản";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<marquee direction="right" scrollamount=20>
    <h1 style="color:aqua">Quản Lý Nhà Xuất Bản</h1>
</marquee>
<hr />
<table class="table table-bordered">
    <tr style="color:yellow">
        <th>
            Mã Nhà Xuất Bản
        </th>
        <th>
            Tên Nhà Xuất Bản
        </th>
        <th>
            Địa Chỉ Nhà Xuất Bản
        </th>
        <th>
            Điện Thoại Nhà Xuất Bản
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="color:black">
            <td>
                @Html.DisplayFor(modelItem => item.MaNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChiNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoaiNXB)
            </td>
            <td>
                <a class="skew-button" href="ChinhSuaNhaXuatBan/@item.MaNXB" title="Chỉnh Sửa"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="skew-button delete-link" href="XoaNhaXuatBan/@item.MaNXB" title="Xóa"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
        </tr>
    }
</table>

<div>
    <a class="skew-button pull-right" href="ThemNhaXuatBan" title="Thêm"><span class="glyphicon glyphicon-plus"></span></a>
</div>

<div>
    @Html.PagedListPager(Model, page => Url.Action("NhaXuatBan", new { page }))
</div>
<hr />
@section Scripts{
    <script>
        $('.delete-link').click(function (e) {
            var a_href = $(this).attr('href');
            e.preventDefault();
            $.ajax({
                url: a_href,
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $('.body-content').prepend(data);
                    $('#deleteModal').modal('show');
                }
            });
        });
    </script>
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyNhaXuatBan/ThemNhaXuatBan.cshtml
@model CuaHangSach.Databases.NHAXUATBAN

@{
    ViewBag.Title = "ThemNhaXuatBan";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

<h2 style="color:aqua">Thêm Nhà Xuất Bản</h2>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="padding-left:10px" class="text-warning">Dấu * là bắt buộc!</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="color:red">
            @Html.LabelFor(model => model.TenNXB, "*Tên Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.DiaChiNXB, "Địa Chỉ Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:yellow">
            @Html.LabelFor(model => model.DienThoaiNXB, "Điện Thoại Nhà Xuất Bản:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoaiNXB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoaiNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <button class="skew-button" type="submit" title="Thêm"><span class="glyphicon glyphicon-plus"></span></button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Về", "NhaXuatBan")
</div>
<hr />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CuaHangSach/CuaHangSach/Areas/Admin/Views/QuanLyNhaXuatBan/XoaNhaXuatBan.cshtml
@model CuaHangSach.Databases.NHAXUATBAN

@{
    ViewBag.Title = "Xóa Nhà Xuất Bản";
    Layout = null;
}

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" style="color:red"><span class="glyphicon glyphicon-warning-sign"></span> Cảnh Báo</h4>
            </div>
            <div class="modal-body">
                <h3>Bạn có chắc muốn xóa nhà xuất bản này không?</h3>
                <div>
                <hr />
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th style="color:blue">Mã Nhà Xuất Bản:</th>
                            <td>@Html.DisplayFor(model => model.MaNXB)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Tên Nhà Xuất Bản:</th>
                            <td>@Html.DisplayFor(model => model.TenNXB)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Địa Chỉ Nhà Xuất Bản:</th>
                            <td>@Html.DisplayFor(model => model.DiaChiNXB)</td>
                        </tr>
                        <tr>
                            <th style="color:blue">Điện Thoại Nhà Xuất Bản:</th>
                            <td>@Html.DisplayFor(model => model.DienThoaiNXB)</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
            @using (Html.BeginForm("XoaNhaXuatBan", "QuanLyNhaXuatBan", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color text-center pull-right">
                    <button type="submit" class="skew-button" title="Xóa"><span class="glyphicon glyphicon-trash"></span></button>
                    <button type="button" class="skew-button" data-dismiss="modal" title="Hủy"><span class="glyphicon glyphicon-remove"></span></button>
                </div>
            }
            </div>
        </div>
    </div>
</div>